"""initial schema

Revision ID: a0db4d78f885
Revises: 
Create Date: 2026-05-03 23:35:47.728159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0db4d78f885'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_organizers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_en', sa.String(length=300), nullable=True),
    sa.Column('domain', sa.String(length=20), nullable=True),
    sa.Column('membership_type', sa.String(length=20), nullable=True),
    sa.Column('homepage', sa.String(length=500), nullable=True),
    sa.Column('departments_json', sa.Text(), nullable=True),
    sa.Column('classification_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academic_organizers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_organizers_name'), ['name'], unique=True)

    op.create_table('crawl_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('doctors_crawled', sa.Integer(), nullable=True),
    sa.Column('schedules_updated', sa.Integer(), nullable=True),
    sa.Column('changes_detected', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('crawler_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_sub', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    op.create_table('academic_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('organizer_name', sa.String(length=300), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('classification_status', sa.String(length=20), nullable=True),
    sa.Column('external_key', sa.String(length=100), nullable=True),
    sa.Column('kma_category', sa.String(length=200), nullable=True),
    sa.Column('kma_eduidx', sa.String(length=50), nullable=True),
    sa.Column('sub_organizer', sa.String(length=300), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('event_code', sa.String(length=100), nullable=True),
    sa.Column('detail_url_external', sa.String(length=500), nullable=True),
    sa.Column('lectures_json', sa.Text(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['academic_organizers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academic_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_events_external_key'), ['external_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_academic_events_is_pinned'), ['is_pinned'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_events_kma_eduidx'), ['kma_eduidx'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_events_organizer_name'), ['organizer_name'], unique=False)

    op.create_table('doctors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('specialty', sa.Text(), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('visit_grade', sa.String(length=1), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_reason', sa.String(length=32), nullable=True),
    sa.Column('linked_doctor_id', sa.Integer(), nullable=True),
    sa.Column('missing_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['linked_doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memo_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('fields', sa.Text(), nullable=False),
    sa.Column('prompt_addon', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('default_report_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memo_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memo_templates_user_id'), ['user_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academic_event_departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['academic_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academic_event_departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_event_departments_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_event_departments_event_id'), ['event_id'], unique=False)

    op.create_table('doctor_date_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('schedule_date', sa.String(length=10), nullable=False),
    sa.Column('time_slot', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('crawled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('time_slot', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.String(length=10), nullable=False),
    sa.Column('period_end', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('source_memo_ids', sa.Text(), nullable=True),
    sa.Column('source_report_ids', sa.Text(), nullable=True),
    sa.Column('raw_combined', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['memo_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('schedule_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.Column('original_day', sa.Integer(), nullable=True),
    sa.Column('original_time_slot', sa.String(length=20), nullable=True),
    sa.Column('new_day', sa.Integer(), nullable=True),
    sa.Column('new_time_slot', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_academic_pins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('pinned_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['academic_events.id'], ),
    sa.ForeignKeyConstraint(['pinned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'event_id', name='uq_team_academic_pin')
    )
    with op.batch_alter_table('team_academic_pins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_academic_pins_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_academic_pins_team_id'), ['team_id'], unique=False)

    op.create_table('team_invitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('inviter_user_id', sa.Integer(), nullable=False),
    sa.Column('invitee_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_invitations_invitee_user_id'), ['invitee_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitations_team_id'), ['team_id'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_user')
    )
    op.create_table('user_academic_pins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['academic_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_user_academic_pin')
    )
    with op.batch_alter_table('user_academic_pins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_academic_pins_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_academic_pins_user_id'), ['user_id'], unique=False)

    op.create_table('user_doctor_grades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=1), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'doctor_id', name='uq_userdoctor_grade')
    )
    with op.batch_alter_table('user_doctor_grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_doctor_grades_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_doctor_grades_user_id'), ['user_id'], unique=False)

    op.create_table('user_doctor_memos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'doctor_id', name='uq_userdoctor_memo')
    )
    with op.batch_alter_table('user_doctor_memos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_doctor_memos_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_doctor_memos_user_id'), ['user_id'], unique=False)

    op.create_table('visit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('product', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('post_notes', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('doctor_name_snapshot', sa.String(length=100), nullable=True),
    sa.Column('doctor_dept_snapshot', sa.String(length=200), nullable=True),
    sa.Column('hospital_name_snapshot', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_logs_visibility'), ['visibility'], unique=False)

    op.create_table('visit_log_recipients',
    sa.Column('visit_log_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_log_id'], ['visit_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('visit_log_id', 'recipient_user_id')
    )
    op.create_table('visits_memo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('visit_log_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.DateTime(), nullable=True),
    sa.Column('memo_type', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('raw_memo', sa.Text(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('doctor_name_snapshot', sa.String(length=100), nullable=True),
    sa.Column('doctor_dept_snapshot', sa.String(length=200), nullable=True),
    sa.Column('hospital_name_snapshot', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['memo_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_log_id'], ['visit_logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visits_memo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_memo_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits_memo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_memo_user_id'))

    op.drop_table('visits_memo')
    op.drop_table('visit_log_recipients')
    with op.batch_alter_table('visit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_logs_visibility'))
        batch_op.drop_index(batch_op.f('ix_visit_logs_user_id'))

    op.drop_table('visit_logs')
    with op.batch_alter_table('user_doctor_memos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_doctor_memos_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_doctor_memos_doctor_id'))

    op.drop_table('user_doctor_memos')
    with op.batch_alter_table('user_doctor_grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_doctor_grades_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_doctor_grades_doctor_id'))

    op.drop_table('user_doctor_grades')
    with op.batch_alter_table('user_academic_pins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_academic_pins_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_academic_pins_event_id'))

    op.drop_table('user_academic_pins')
    op.drop_table('team_members')
    with op.batch_alter_table('team_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_invitations_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_invitations_status'))
        batch_op.drop_index(batch_op.f('ix_team_invitations_invitee_user_id'))

    op.drop_table('team_invitations')
    with op.batch_alter_table('team_academic_pins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_academic_pins_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_academic_pins_event_id'))

    op.drop_table('team_academic_pins')
    op.drop_table('schedule_changes')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))

    op.drop_table('reports')
    op.drop_table('doctor_schedules')
    op.drop_table('doctor_date_schedules')
    with op.batch_alter_table('academic_event_departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_event_departments_event_id'))
        batch_op.drop_index(batch_op.f('ix_academic_event_departments_department'))

    op.drop_table('academic_event_departments')
    op.drop_table('teams')
    with op.batch_alter_table('memo_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memo_templates_user_id'))

    op.drop_table('memo_templates')
    op.drop_table('doctors')
    with op.batch_alter_table('academic_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_events_organizer_name'))
        batch_op.drop_index(batch_op.f('ix_academic_events_kma_eduidx'))
        batch_op.drop_index(batch_op.f('ix_academic_events_is_pinned'))
        batch_op.drop_index(batch_op.f('ix_academic_events_external_key'))

    op.drop_table('academic_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('hospitals')
    op.drop_table('crawl_logs')
    with op.batch_alter_table('academic_organizers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_organizers_name'))

    op.drop_table('academic_organizers')
    # ### end Alembic commands ###
